"""Tools module for Cyber-AutoAgent."""

from modules.tools.memory import (
    Mem0ServiceClient,
    get_memory_client,
    initialize_memory_system,
    mem0_store,
    mem0_get,
    mem0_retrieve,
    mem0_list,
    mem0_delete,
    mem0_store_plan,
    mem0_get_plan,
    mem0_create_tasks,
    mem0_list_uncompleted_tasks,
    mem0_task_done,
    mem0_get_active_task,
)
from modules.tools.browser import (
    initialize_browser,
    browser_goto_url,
    browser_observe_page,
    browser_get_page_html,
    browser_set_headers,
    browser_perform_action,
    browser_evaluate_js,
    browser_get_cookies,
)
from modules.tools.mcp import (
    discover_mcp_tools,
)
from modules.tools.channels import (
    channel_create_forward,
    channel_create_reverse,
    channel_send,
    channel_poll,
    channel_status,
    channel_close,
    channel_close_all,
)
from modules.tools.prompt_optimizer import prompt_optimizer
from modules.tools.oast import (
    oast_health,
    oast_endpoints,
    oast_poll,
    oast_register_http_response,
    oast_clear_http_responses,
    close_oast_providers,
)

__all__ = [
    "mem0_store",
    "mem0_get",
    "mem0_retrieve",
    "mem0_list",
    "mem0_delete",
    "mem0_store_plan",
    "mem0_get_plan",
    "mem0_create_tasks",
    "mem0_list_uncompleted_tasks",
    "mem0_task_done",
    "mem0_get_active_task",
    "initialize_memory_system",
    "get_memory_client",
    "Mem0ServiceClient",
    "initialize_browser",
    "browser_set_headers",
    "browser_goto_url",
    "browser_observe_page",
    "browser_get_page_html",
    "browser_perform_action",
    "browser_get_cookies",
    "browser_evaluate_js",
    "prompt_optimizer",
    "discover_mcp_tools",
    "channel_create_forward",
    "channel_create_reverse",
    "channel_send",
    "channel_poll",
    "channel_status",
    "channel_close",
    "channel_close_all",
    "oast_health",
    "oast_endpoints",
    "oast_poll",
    "oast_register_http_response",
    "oast_clear_http_responses",
    "close_oast_providers",
]
